import { DistanceMeasures, DistanceType, Label, Tabs } from "../types/types";
import Car from "../assets/img/car-svgrepo-com.svg";
import Plane from "../assets/img/airplane-departure-svgrepo-com.svg";
import House from "../assets/img/house-svgrepo-com.svg";
import Train from "../assets/img/train-svgrepo-com.svg";
import Secondary from "../assets/img/money-bag-svgrepo-com.svg";

import * as Components from "../components/index";

export const TabsData: Tabs = [
  {
    id: 0,
    text: "HouseHold",
    img: House,
    Component: Components.Household,
  },
  {
    id: 1,
    text: "Private Transport",
    img: Car,
    Component: Components.Private,
  },
  {
    id: 2,
    text: "Airplane",
    img: Plane,
    Component: Components.Airplane,
  },
  {
    id: 3,
    text: "Public Transport",
    img: Train,
    Component: Components.Public,
  },
  {
    id: 4,
    text: "Secondary",
    img: Secondary,
    Component: Components.Secondary,
  },
];

export const Langs: string[] = ["EN"]; //"RU", "KZ"

export const DistanceMeasure: DistanceMeasures = [
  {
    text: "km",
    value: 1,
  },
  {
    text: "mile",
    value: 0.621371,
  },
];

export const HouseholdMeasures = [
  {
    text: "kWh",
  },
  {
    text: "kg",
  },
  {
    text: "m³",
  },
];

export const Fields: Array<{ text: string; measures: string[] }> = [
  {
    text: "Electricity",
    measures: ["kWh"],
  },
  {
    text: "Natural Gas",
    measures: ["kWh", "kg", "m³"],
  },
  {
    text: "Biomass",
    measures: ["kWh", "kg"],
  },
  {
    text: "Coal",
    measures: ["kWh", "kg"],
  },
  {
    text: "Heating Oil",
    measures: ["kWh", "kg", "litres"],
  },
  {
    text: "LPG",
    measures: ["kWh", "kg", "litres"],
  },
];

export const DistanceFields = { text: "Distance", measures: ["km", "mile"] };

export const CarFuelTypes = {
  text: "Car Fuel Type",
  measures: ["Petrol", "Diesel", "Hybrid", "Electricity"],
};

export const CarTypes = {
  text: "Car Type",
  vehicle: "car",
  measures: ["Small", "Medium", "Large"],
};

export const MotorBikeFuelTypes = {
  text: "Motorcycle Fuel Type",
  vehicle: "motorcycle",
  measures: ["Petrol", "Diesel", "Electricity"],
};

export const FlightTripTypes: string[] = ["one-way", "round-trip"];

export const FlightClass: string[] = ["economy", "business", "first"];

export const FlightTripsNumber: number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

export const Cities: string[] = [
  "Astana",
  "Almaty",
  "Aktau",
  "Aktobe",
  "Atyrau",
  "Zhezkazgan",
  "Karagandy",
  "Kyzylorda",
  "Kokshetau",
  "Kostanay",
  "Pavlodar",
  "Petropavlovsk",
  "Semey",
  "Taldykorgan",
  "Taraz",
  "Uralsk",
  "Oskemen",
  "Shymkent",
];

export const PublicTransport: Array<{ text: string; measures: string[] }> = [
  {
    text: "Bus",
    measures: ["km", "mile"],
  },
  {
    text: "Train",
    measures: ["km", "mile"],
  },
  {
    text: "Taxi",
    measures: ["km", "mile"],
  },
  {
    text: "Tram",
    measures: ["km", "mile"],
  },
  {
    text: "Subway",
    measures: ["km", "mile"],
  },
];

export const SecondaryLabels: Label[] = [
  { text: "Eating Out", value: "eatingout" },
  { text: "Car Maintenance", value: "carmaintaince" },
  { text: "Clothing", value: "clothing" },
  { text: "Furniture", value: "furniture" },
  { text: "Domestic Water", value: "domesticwater" },
  { text: "Telephone & Internet", value: "telephoneinternet" },
  { text: "Computers & Electronics", value: "computerelectronics" },
  { text: "Electrical Appliances", value: "electricalappliainces" },
  { text: "Postage & Couriers", value: "postage" },
  { text: "Magazines & Books", value: "magazine" },
  { text: "Stationery", value: "stationery" },
  { text: "Cleaning Products", value: "cleaning" },
  { text: "Hair & Self-care", value: "hair" },
  { text: "Pet Food", value: "petfood" },
  { text: "Hotel Stays", value: "hotel" },
  { text: "Insurance", value: "insurance" },
  { text: "Other Legal Services", value: "other" },
];

export const distances: DistanceType = [
  { from: "Astana", to: "Astana", distance: 0 },
  { from: "Astana", to: "Almaty", distance: 951.61 },
  { from: "Astana", to: "Aktau", distance: 1720.9 },
  { from: "Astana", to: "Aktobe", distance: 1008.98 },
  { from: "Astana", to: "Atyrau", distance: 1491.85 },
  { from: "Astana", to: "Zhezkazgan", distance: 457.42 },
  { from: "Astana", to: "Karagandy", distance: 200.56 },
  { from: "Astana", to: "Kyzylorda", distance: 828.07 },
  { from: "Astana", to: "Kokshetau", distance: 286.83 },
  { from: "Astana", to: "Kostanay", distance: 592.89 },
  { from: "Astana", to: "Pavlodar", distance: 408.89 },
  { from: "Astana", to: "Petropavlovsk", distance: 444.87 },  
  { from: "Astana", to: "Semey", distance: 622.46 },
  { from: "Astana", to: "Taldykorgan", distance: 836.2 },
  { from: "Astana", to: "Taraz", distance: 909.41 },
  { from: "Astana", to: "Uralsk", distance: 1388.98 },
  { from: "Astana", to: "Oskemen", distance: 787.24 },
  { from: "Astana", to: "Shymkent", distance: 975.59 },
  { from: "Almaty", to: "Astana", distance: 951.61 },
  { from: "Almaty", to: "Almaty", distance: 0 },
  { from: "Almaty", to: "Aktau", distance: 2083.77 },
  { from: "Almaty", to: "Aktobe", distance: 1687.92 },
  { from: "Almaty", to: "Atyrau", distance: 2011.59 },
  { from: "Almaty", to: "Zhezkazgan", distance: 871.96 },
  { from: "Almaty", to: "Karagandy", distance: 758.3 },
  { from: "Almaty", to: "Kyzylorda", distance: 927.78 },
  { from: "Almaty", to: "Kokshetau", distance: 1238.2 },
  { from: "Almaty", to: "Kostanay", distance: 1479.17 },
  { from: "Almaty", to: "Pavlodar", distance: 984.39 },
  { from: "Almaty", to: "Petropavlovsk", distance: 1392.63 },
  { from: "Almaty", to: "Semey", distance: 816.01 },
  { from: "Almaty", to: "Taldykorgan", distance: 226.58 },
  { from: "Almaty", to: "Taraz", distance: 469.48 },
  { from: "Almaty", to: "Uralsk", distance: 2099.18 },
  { from: "Almaty", to: "Oskemen", distance: 852.16 },
  { from: "Almaty", to: "Shymkent", distance: 626.53 },
  { from: "Aktau", to: "Astana", distance: 1008.98 },
  { from: "Aktau", to: "Almaty", distance: 2083.77 },
  { from: "Aktau", to: "Aktau", distance: 0 },
  { from: "Aktau", to: "Aktobe", distance: 848.12 },
  { from: "Aktau", to: "Atyrau", distance: 367.54 },
  { from: "Aktau", to: "Zhezkazgan", distance: 1357.86 },
  { from: "Aktau", to: "Karagandy", distance: 1806.9 },
  { from: "Aktau", to: "Kyzylorda", distance: 1157.89 },
  { from: "Aktau", to: "Kokshetau", distance: 1713.83 },
  { from: "Aktau", to: "Kostanay", distance: 1383.85 },
  { from: "Aktau", to: "Pavlodar", distance: 2129.73 },
  { from: "Aktau", to: "Petropavlovsk", distance: 1904.11 },
  { from: "Aktau", to: "Semey", distance: 2306.01 },
  { from: "Aktau", to: "Taldykorgan", distance: 2166.08 },
  { from: "Aktau", to: "Taraz", distance: 1635.66 },
  { from: "Aktau", to: "Uralsk", distance: 812.31 },
  { from: "Aktau", to: "Oskemen", distance: 2462.98 },
  { from: "Aktau", to: "Shymkent", distance: 1500.32 },
  { from: "Aktobe", to: "Astana", distance: 1491.85 },
  { from: "Aktobe", to: "Almaty", distance: 2011.59 },
  { from: "Aktobe", to: "Aktau", distance: 848.12 },
  { from: "Aktobe", to: "Aktobe", distance: 0 },
  { from: "Aktobe", to: "Atyrau", distance: 526.62 },
  { from: "Aktobe", to: "Zhezkazgan", distance: 818.5 },
  { from: "Aktobe", to: "Karagandy", distance: 1154.53 },
  { from: "Aktobe", to: "Kyzylorda", distance: 881.18 },
  { from: "Aktobe", to: "Kokshetau", distance: 917.99 },
  { from: "Aktobe", to: "Kostanay", distance: 547.37 },
  { from: "Aktobe", to: "Pavlodar", distance: 1397.52 },
  { from: "Aktobe", to: "Petropavlovsk", distance: 953.43 },
  { from: "Aktobe", to: "Semey", distance: 1630.97 },
  { from: "Aktobe", to: "Taldykorgan", distance: 1683.54 },
  { from: "Aktobe", to: "Taraz", distance: 1353.43 },
  { from: "Aktobe", to: "Uralsk", distance: 411.74 },
  { from: "Aktobe", to: "Oskemen", distance: 1795.58 },
  { from: "Aktobe", to: "Shymkent", distance: 1285.56 },
  { from: "Atyrau", to: "Astana", distance: 457.42 },
  { from: "Atyrau", to: "Almaty", distance: 871.96 },
  { from: "Atyrau", to: "Aktau", distance: 1357.86 },
  { from: "Atyrau", to: "Aktobe", distance: 818.5 },
  { from: "Atyrau", to: "Atyrau", distance: 0 },
  { from: "Atyrau", to: "Zhezkazgan", distance: 1198.27 },
  { from: "Atyrau", to: "Karagandy", distance: 1609.43 },
  { from: "Atyrau", to: "Kyzylorda", distance: 1098.3 },
  { from: "Atyrau", to: "Kokshetau", distance: 1436.56 },
  { from: "Atyrau", to: "Kostanay", distance: 1073.99 },
  { from: "Atyrau", to: "Pavlodar", distance: 1894.2 },
  { from: "Atyrau", to: "Petropavlovsk", distance: 1479.66 },
  { from: "Atyrau", to: "Semey", distance: 2103.42 },
  { from: "Atyrau", to: "Taldykorgan", distance: 2055.99 },
  { from: "Atyrau", to: "Taraz", distance: 1600.87 },
  { from: "Atyrau", to: "Uralsk", distance: 448.95 },
  { from: "Atyrau", to: "Oskemen", distance: 2265.8 },
  { from: "Atyrau", to: "Shymkent", distance: 1489.16 },
  { from: "Zhezkazgan", to: "Astana", distance: 200.56 },
  { from: "Zhezkazgan", to: "Almaty", distance: 758.3 },
  { from: "Zhezkazgan", to: "Aktau", distance: 1806.9 },
  { from: "Zhezkazgan", to: "Aktobe", distance: 1154.53 },
  { from: "Zhezkazgan", to: "Atyrau", distance: 1609.43 },
  { from: "Zhezkazgan", to: "Zhezkazgan", distance: 0 },
  { from: "Zhezkazgan", to: "Karagandy", distance: 465.82 },
  { from: "Zhezkazgan", to: "Kyzylorda", distance: 372.56 },
  { from: "Zhezkazgan", to: "Kokshetau", distance: 639.36 },
  { from: "Zhezkazgan", to: "Kostanay", distance: 679.83 },
  { from: "Zhezkazgan", to: "Pavlodar", distance: 833.83 },
  { from: "Zhezkazgan", to: "Petropavlovsk", distance: 793.01 },
  { from: "Zhezkazgan", to: "Semey", distance: 957.33 },
  { from: "Zhezkazgan", to: "Taldykorgan", distance: 869.96 },
  { from: "Zhezkazgan", to: "Taraz", distance: 608.33 },
  { from: "Zhezkazgan", to: "Uralsk", distance: 1230.23 },
  { from: "Zhezkazgan", to: "Oskemen", distance: 1109.41 },
  { from: "Zhezkazgan", to: "Shymkent", distance: 610.51 },
  { from: "Karagandy", to: "Astana", distance: 828.07 },
  { from: "Karagandy", to: "Almaty", distance: 927.78 },
  { from: "Karagandy", to: "Aktau", distance: 1806.9 },
  { from: "Karagandy", to: "Aktobe", distance: 1154.53 },
  { from: "Karagandy", to: "Atyrau", distance: 1609.43 },
  { from: "Karagandy", to: "Zhezkazgan", distance: 465.82 },
  { from: "Karagandy", to: "Karagandy", distance: 0 },
  { from: "Karagandy", to: "Kyzylorda", distance: 804.44 },
  { from: "Karagandy", to: "Kokshetau", distance: 482.56 },
  { from: "Karagandy", to: "Kostanay", distance: 783.82 },
  { from: "Karagandy", to: "Pavlodar", distance: 384.32 },
  { from: "Karagandy", to: "Petropavlovsk", distance: 634.45 },
  { from: "Karagandy", to: "Semey", distance: 499.2 },
  { from: "Karagandy", to: "Taldykorgan", distance: 635.7 },
  { from: "Karagandy", to: "Taraz", distance: 774.74 },
  { from: "Karagandy", to: "Uralsk", distance: 1548.91 },
  { from: "Karagandy", to: "Oskemen", distance: 658.26 },
  { from: "Karagandy", to: "Shymkent", distance: 865.96 },
  { from: "Kyzylorda", to: "Astana", distance: 592.89 },
  { from: "Kyzylorda", to: "Almaty", distance: 1479.17 },
  { from: "Kyzylorda", to: "Aktau", distance: 1157.89 },
  { from: "Kyzylorda", to: "Aktobe", distance: 881.18 },
  { from: "Kyzylorda", to: "Atyrau", distance: 1098.3 },
  { from: "Kyzylorda", to: "Zhezkazgan", distance: 372.56 },
  { from: "Kyzylorda", to: "Karagandy", distance: 804.44 },
  { from: "Kyzylorda", to: "Kyzylorda", distance: 0 },
  { from: "Kyzylorda", to: "Kokshetau", distance: 1002.89 },
  { from: "Kyzylorda", to: "Kostanay", distance: 957.81 },
  { from: "Kyzylorda", to: "Pavlodar", distance: 1186.24 },
  { from: "Kyzylorda", to: "Petropavlovsk", distance: 1149.7 },
  { from: "Kyzylorda", to: "Semey", distance: 1903.06 },
  { from: "Kyzylorda", to: "Taldykorgan", distance: 1012.98 },
  { from: "Kyzylorda", to: "Taraz", distance: 503.1 },
  { from: "Kyzylorda", to: "Uralsk", distance: 1266.61 },
  { from: "Kyzylorda", to: "Oskemen", distance: 1401.4 },
  { from: "Kyzylorda", to: "Shymkent", distance: 407.81 },
  { from: "Kokshetau", to: "Astana", distance: 408.89 },
  { from: "Kokshetau", to: "Almaty", distance: 984.39 },
  { from: "Kokshetau", to: "Aktau", distance: 2129.73 },
  { from: "Kokshetau", to: "Aktobe", distance: 1397.52 },
  { from: "Kokshetau", to: "Atyrau", distance: 1894.2 },
  { from: "Kokshetau", to: "Zhezkazgan", distance: 833.83 },
  { from: "Kokshetau", to: "Karagandy", distance: 384.32 },
  { from: "Kokshetau", to: "Kyzylorda", distance: 1186.24 },
  { from: "Kokshetau", to: "Kokshetau", distance: 0 },
  { from: "Kokshetau", to: "Kostanay", distance: 519.13 },
  { from: "Kokshetau", to: "Pavlodar", distance: 163.1 },
  { from: "Kokshetau", to: "Petropavlovsk", distance: 802.34 },
  { from: "Kokshetau", to: "Semey", distance: 1260.25 },
  { from: "Kokshetau", to: "Taldykorgan", distance: 597.28 },
  { from: "Kokshetau", to: "Taraz", distance: 1115.49 },
  { from: "Kokshetau", to: "Uralsk", distance: 1172.94 },
  { from: "Kokshetau", to: "Oskemen", distance: 1250.62 },
  { from: "Kokshetau", to: "Shymkent", distance: 961.09 },
  { from: "Kostanay", to: "Astana", distance: 592.89 },
  { from: "Kostanay", to: "Almaty", distance: 1479.17 },
  { from: "Kostanay", to: "Aktau", distance: 1383.85 },
  { from: "Kostanay", to: "Aktobe", distance: 547.37 },
  { from: "Kostanay", to: "Atyrau", distance: 1073.99 },
  { from: "Kostanay", to: "Zhezkazgan", distance: 679.83 },
  { from: "Kostanay", to: "Karagandy", distance: 783.82 },
  { from: "Kostanay", to: "Kyzylorda", distance: 957.81 },
  { from: "Kostanay", to: "Kokshetau", distance: 402.52 },
  { from: "Kostanay", to: "Kostanay", distance: 0 },
  { from: "Kostanay", to: "Pavlodar", distance: 917.78 },
  { from: "Kostanay", to: "Petropavlovsk", distance: 407.75 },
  { from: "Kostanay", to: "Semey", distance: 1189.15 },
  { from: "Kostanay", to: "Taldykorgan", distance: 1903.11 },
  { from: "Kostanay", to: "Taraz", distance: 1287.21 },
  { from: "Kostanay", to: "Uralsk", distance: 849.83 },
  { from: "Kostanay", to: "Oskemen", distance: 1351.51 },
  { from: "Kostanay", to: "Shymkent", distance: 1284.79 },
  { from: "Pavlodar", to: "Astana", distance: 408.89 },
  { from: "Pavlodar", to: "Almaty", distance: 984.39 },
  { from: "Pavlodar", to: "Aktau", distance: 2129.73 },
  { from: "Pavlodar", to: "Aktobe", distance: 1397.52 },
  { from: "Pavlodar", to: "Atyrau", distance: 1894.2 },
  { from: "Pavlodar", to: "Zhezkazgan", distance: 833.83 },
  { from: "Pavlodar", to: "Karagandy", distance: 384.32 },
  { from: "Pavlodar", to: "Kyzylorda", distance: 1186.24 },
  { from: "Pavlodar", to: "Kokshetau", distance: 163.1 },
  { from: "Pavlodar", to: "Kostanay", distance: 917.78 },
  { from: "Pavlodar", to: "Pavlodar", distance: 0 },
  { from: "Pavlodar", to: "Petropavlovsk", distance: 595.82 },
  { from: "Pavlodar", to: "Semey", distance: 300.89 },
  { from: "Pavlodar", to: "Taldykorgan", distance: 793.67 },
  { from: "Pavlodar", to: "Taraz", distance: 1125.83 },
  { from: "Pavlodar", to: "Uralsk", distance: 448.38 },
  { from: "Pavlodar", to: "Oskemen", distance: 1233.98 },
  { from: "Pavlodar", to: "Shymkent", distance: 1381.66 },
  { from: "Petropavlovsk", to: "Astana", distance: 444.87 },
  { from: "Petropavlovsk", to: "Almaty", distance: 1392.63 },
  { from: "Petropavlovsk", to: "Aktau", distance: 1904.11 },
  { from: "Petropavlovsk", to: "Aktobe", distance: 953.43 },
  { from: "Petropavlovsk", to: "Atyrau", distance: 1479.66 },
  { from: "Petropavlovsk", to: "Zhezkazgan", distance: 793.01 },
  { from: "Petropavlovsk", to: "Karagandy", distance: 634.45 },
  { from: "Petropavlovsk", to: "Kyzylorda", distance: 1149.7 },
  { from: "Petropavlovsk", to: "Kokshetau", distance: 802.34 },
  { from: "Petropavlovsk", to: "Kostanay", distance: 407.75 },
  { from: "Petropavlovsk", to: "Pavlodar", distance: 595.82 },
  { from: "Petropavlovsk", to: "Petropavlovsk", distance: 0 },
  { from: "Petropavlovsk", to: "Semey", distance: 893.76 },
  { from: "Petropavlovsk", to: "Taldykorgan", distance: 1260.25 },
  { from: "Petropavlovsk", to: "Taraz", distance: 1335.92 },
  { from: "Petropavlovsk", to: "Uralsk", distance: 1245.75 },
  { from: "Petropavlovsk", to: "Oskemen", distance: 1902.11 },
  { from: "Petropavlovsk", to: "Shymkent", distance: 1211.42 },
  { from: "Semey", to: "Astana", distance: 622.46 },
  { from: "Semey", to: "Almaty", distance: 816.01 },
  { from: "Semey", to: "Aktau", distance: 2306.01 },
  { from: "Semey", to: "Aktobe", distance: 1630.97 },
  { from: "Semey", to: "Atyrau", distance: 2103.42 },
  { from: "Semey", to: "Zhezkazgan", distance: 957.33 },
  { from: "Semey", to: "Karagandy", distance: 499.2 },
  { from: "Semey", to: "Kyzylorda", distance: 1903.06 },
  { from: "Semey", to: "Kokshetau", distance: 1260.25 },
  { from: "Semey", to: "Kostanay", distance: 1189.15 },
  { from: "Semey", to: "Pavlodar", distance: 300.89 },
  { from: "Semey", to: "Petropavlovsk", distance: 893.76 },
  { from: "Semey", to: "Semey", distance: 0 },
  { from: "Semey", to: "Taldykorgan", distance: 597.28 },
  { from: "Semey", to: "Taraz", distance: 1076.93 },
  { from: "Semey", to: "Uralsk", distance: 164.81 },
  { from: "Semey", to: "Oskemen", distance: 1211.42 },
  { from: "Semey", to: "Shymkent", distance: 1076.93 },
  { from: "Taldykorgan", to: "Astana", distance: 836.2 },
  { from: "Taldykorgan", to: "Almaty", distance: 226.58 },
  { from: "Taldykorgan", to: "Aktau", distance: 2166.08 },
  { from: "Taldykorgan", to: "Aktobe", distance: 1683.54 },
  { from: "Taldykorgan", to: "Atyrau", distance: 2055.99 },
  { from: "Taldykorgan", to: "Zhezkazgan", distance: 869.96 },
  { from: "Taldykorgan", to: "Karagandy", distance: 635.7 },
  { from: "Taldykorgan", to: "Kyzylorda", distance: 1012.98 },
  { from: "Taldykorgan", to: "Kokshetau", distance: 624.78 },
  { from: "Taldykorgan", to: "Kostanay", distance: 1903.11 },
  { from: "Taldykorgan", to: "Pavlodar", distance: 793.67 },
  { from: "Taldykorgan", to: "Petropavlovsk", distance: 1260.25 },
  { from: "Taldykorgan", to: "Semey", distance: 597.28 },
  { from: "Taldykorgan", to: "Taldykorgan", distance: 0 },
  { from: "Taldykorgan", to: "Taraz", distance: 624.78 },
  { from: "Taldykorgan", to: "Uralsk", distance: 2094.14 },
  { from: "Taldykorgan", to: "Oskemen", distance: 625.73 },
  { from: "Taldykorgan", to: "Shymkent", distance: 782.98 },
  { from: "Taraz", to: "Astana", distance: 909.41 },
  { from: "Taraz", to: "Almaty", distance: 469.48 },
  { from: "Taraz", to: "Aktau", distance: 1635.66 },
  { from: "Taraz", to: "Aktobe", distance: 1353.43 },
  { from: "Taraz", to: "Atyrau", distance: 1600.87 },
  { from: "Taraz", to: "Zhezkazgan", distance: 608.33 },
  { from: "Taraz", to: "Karagandy", distance: 774.74 },
  { from: "Taraz", to: "Kyzylorda", distance: 503.1 },
  { from: "Taraz", to: "Kokshetau", distance: 1115.49 },
  { from: "Taraz", to: "Kostanay", distance: 1287.21 },
  { from: "Taraz", to: "Pavlodar", distance: 1125.83 },
  { from: "Taraz", to: "Petropavlovsk", distance: 1335.92 },
  { from: "Taraz", to: "Semey", distance: 1076.93 },
  { from: "Taraz", to: "Taldykorgan", distance: 624.78 },
  { from: "Taraz", to: "Taraz", distance: 0 },
  { from: "Taraz", to: "Uralsk", distance: 1753.31 },
  { from: "Taraz", to: "Oskemen", distance: 1170.8 },
  { from: "Taraz", to: "Shymkent", distance: 159.11 },
  { from: "Uralsk", to: "Astana", distance: 1388.98 },
  { from: "Uralsk", to: "Almaty", distance: 2099.18 },
  { from: "Uralsk", to: "Aktau", distance: 812.31 },
  { from: "Uralsk", to: "Aktobe", distance: 411.74 },
  { from: "Uralsk", to: "Atyrau", distance: 448.95 },
  { from: "Uralsk", to: "Zhezkazgan", distance: 1230.23 },
  { from: "Uralsk", to: "Karagandy", distance: 1548.91 },
  { from: "Uralsk", to: "Kyzylorda", distance: 1266.61 },
  { from: "Uralsk", to: "Kokshetau", distance: 1172.94 },
  { from: "Uralsk", to: "Kostanay", distance: 849.83 },
  { from: "Uralsk", to: "Pavlodar", distance: 448.38 },
  { from: "Uralsk", to: "Petropavlovsk", distance: 1245.75 },
  { from: "Uralsk", to: "Semey", distance: 164.81 },
  { from: "Uralsk", to: "Taldykorgan", distance: 2094.14 },
  { from: "Uralsk", to: "Taraz", distance: 1753.31 },
  { from: "Uralsk", to: "Uralsk", distance: 0 },
  { from: "Uralsk", to: "Oskemen", distance: 2174.56 },
  { from: "Uralsk", to: "Shymkent", distance: 1674.37 },
  { from: "Oskemen", to: "Astana", distance: 787.24 },
  { from: "Oskemen", to: "Almaty", distance: 852.16 },
  { from: "Oskemen", to: "Aktau", distance: 2462.98 },
  { from: "Oskemen", to: "Aktobe", distance: 1795.58 },
  { from: "Oskemen", to: "Atyrau", distance: 2265.8 },
  { from: "Oskemen", to: "Zhezkazgan", distance: 1109.41 },
  { from: "Oskemen", to: "Karagandy", distance: 658.26 },
  { from: "Oskemen", to: "Kyzylorda", distance: 1401.4 },
  { from: "Oskemen", to: "Kokshetau", distance: 1250.62 },
  { from: "Oskemen", to: "Kostanay", distance: 1351.51 },
  { from: "Oskemen", to: "Pavlodar", distance: 1233.98 },
  { from: "Oskemen", to: "Petropavlovsk", distance: 1902.11 },
  { from: "Oskemen", to: "Semey", distance: 1211.42 },
  { from: "Oskemen", to: "Taldykorgan", distance: 625.73 },
  { from: "Oskemen", to: "Taraz", distance: 1170.8 },
  { from: "Oskemen", to: "Uralsk", distance: 2174.56 },
  { from: "Oskemen", to: "Oskemen", distance: 0 },
  { from: "Oskemen", to: "Shymkent", distance: 1313.94 },
  { from: "Shymkent", to: "Astana", distance: 975.59 },
  { from: "Shymkent", to: "Almaty", distance: 626.53 },
  { from: "Shymkent", to: "Aktau", distance: 1500.32 },
  { from: "Shymkent", to: "Aktobe", distance: 1285.56 },
  { from: "Shymkent", to: "Atyrau", distance: 1489.16 },
  { from: "Shymkent", to: "Zhezkazgan", distance: 610.51 },
  { from: "Shymkent", to: "Karagandy", distance: 865.96 },
  { from: "Shymkent", to: "Kyzylorda", distance: 407.81 },
  { from: "Shymkent", to: "Kokshetau", distance: 1220.64 },
  { from: "Shymkent", to: "Kostanay", distance: 1284.79 },
  { from: "Shymkent", to: "Pavlodar", distance: 1381.66 },
  { from: "Shymkent", to: "Petropavlovsk", distance: 1211.42 },
  { from: "Shymkent", to: "Semey", distance: 1076.93 },
  { from: "Shymkent", to: "Taldykorgan", distance: 782.98 },
  { from: "Shymkent", to: "Taraz", distance: 159.11 },
  { from: "Shymkent", to: "Uralsk", distance: 1674.37 },
  { from: "Shymkent", to: "Oskemen", distance: 1313.94 },
  { from: "Shymkent", to: "Shymkent", distance: 0 },
];
